
name: Run test
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        ruby-version: [2.7, 3.0, 3.1, 3.2]
    run-on: ubuntu-latest
    name: ${{ format('Tests (Ruby {0})', matrix.ruby-version) }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run test
        run: rspec
